title: Oluwatoyosi Ogunniyi # your name (or website title) here
logo: "/images/Portfolio Pic_Main.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 A motivated and results-driven data scientist possessing the ability to translate complex data and help organizations gain insights and make data-driven decisions using required tools.
 <br><br>
 
 Technical Skills: Python, Scikit-learn, R Programming, MySQL, Advanced Excel, Tableau, Microsoft Azure
 <br><br>
 General Skills: Statistical Analysis, Data Visualization, Machine Learning, Deep Learning, Data Preparation, Database Management, Research, Big Data Analytics
 <br><br>
 
  <a href="https://www.linkedin.com/in/oluwatoyosiogunniyi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
