title: Oluwatoyosi Ogunniyi # your name (or website title) here
logo: "/images/Portfolio Pic_Main.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 
 Skills
 <br><br>
 Technical: Python, Scikit-learn, R Programming, SQL, Advanced Excel, Tableau, Microsoft Azure
 General: Statistical Analysis and Data Visualization, Machine Learning, Deep Learning, Data Preparation
  
 An highly skilled data scientist with the ability to translate complex data into actionable insights and to help organizations gain insights and make data-driven decisions using required tools.
  <br><br>
  <a href="https://www.linkedin.com/in/oluwatoyosiogunniyi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
